name: ci 
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    # ...
    - uses: peaceiris/actions-gh-pages@v3
      name: Build Documentation
      with:
        args: docfx_project/docfx.json

    # Publish generated site using GitHub Pages
    - uses: peaceiris/actions-gh-pages@v3
      name: Publish Documentation on GitHub Pages
      env:
        BUILD_DIR: _site # docfx's default output directory is _site
        GH_PAT: ${{ secrets.GH_PAT }} # See https://github.com/maxheld83/ghpages