name: pages
on:
  push:
    branches:
      - main
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x
      - name: Build 🔧
        run: dotnet build -p:BuildDocFx=true
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: $
          BRANCH: gh-pages
          FOLDER: _site